# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pricey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pricey
  pod 'Parse'
  pod 'AlamofireImage'

  target 'PriceyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PriceyUITests' do
    # Pods for testing
  end

end
